webtalk_init -webtalk_dir /home/maar/stdy/4c/SVViPU/lab3/microbblaze/microbblaze.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 19 18:00:39 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "599daf52-4031-4b93-b4bc-fdf79b6b5550" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b095f25068554579b4b9790e6381611d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "325" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2797.691 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "121 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "9.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "147012_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3328901923 -regid "" -xml /home/maar/stdy/4c/SVViPU/lab3/microbblaze/microbblaze.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/maar/stdy/4c/SVViPU/lab3/microbblaze/microbblaze.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/maar/stdy/4c/SVViPU/lab3/microbblaze/microbblaze.sim/sim_1/behav/xsim/xsim.dir/sim_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
